services:
  - type: web
    name: azure-patient-api
    env: python
    buildCommand: |
      bash build.sh
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: AZURE_SQL_SERVER
        value: tcp:azuredatabase001.database.windows.net
      - key: AZURE_SQL_DATABASE
        value: azuredatabase1
      - key: AZURE_SQL_USERNAME
        value: Avesh01
      - key: AZURE_SQL_PASSWORD
        value: YourActualPasswordHere
      - key: RENDER
        value: "true"
